# This file will be used to facilitate the compilation and execution
# of programs made in java.
# Requirements
# * javac, java compiler.
#  *java, starts the java runtime enviromrnt, loading a specified class, and calling the main method.

JFLAGS = -g
JC = javac 
